/**
 * Başlangıç içeriği — boş bir veritabanı kurulurken kullanılır.
 * Alan adları Prisma şemasıyla aynı. Görseller burada yok; onları
 * `npm run mock` yükler.
 */

export const categories = [
  {
    "slug": "rack-sunucular",
    "status": "PUBLISHED" as const,
    "sort": 0,
    "families": "ThinkSystem SR",
    "name": "Rack Sunucular",
    "desc": "Standart 19\" kabine monte edilen 1U–8U sunucular. Kurumsal iş yüklerinin büyük çoğunluğu burada."
  },
  {
    "slug": "kule-sunucular",
    "status": "PUBLISHED" as const,
    "sort": 1,
    "families": "ThinkSystem ST",
    "name": "Kule Sunucular",
    "desc": "Kabin gerektirmeyen, ofis ortamında çalışabilen dikey gövde. Küçük işletme ve şube için."
  },
  {
    "slug": "gpu-ai-sunuculari",
    "status": "PUBLISHED" as const,
    "sort": 2,
    "families": "ThinkSystem SR / SD",
    "name": "GPU & Yapay Zekâ Sunucuları",
    "desc": "Model eğitimi ve çıkarım için 4–8 GPU taşıyan gövdeler; sıvı soğutmalı seçenekler dahil."
  },
  {
    "slug": "edge-sunucular",
    "status": "PUBLISHED" as const,
    "sort": 3,
    "families": "ThinkEdge SE",
    "name": "Edge & Şube Sunucuları",
    "desc": "Veri merkezi dışında, mağaza ve üretim sahasında çalışacak kompakt ve dayanıklı gövdeler."
  },
  {
    "slug": "depolama",
    "status": "PUBLISHED" as const,
    "sort": 4,
    "families": "ThinkSystem DM / DG / DE",
    "name": "Depolama Sistemleri",
    "desc": "Blok ve dosya tabanlı diziler, tam flash ve hibrit seçenekler."
  },
  {
    "slug": "yuksek-yogunluk",
    "status": "PUBLISHED" as const,
    "sort": 5,
    "families": "ThinkSystem SD / SR",
    "name": "Yüksek Yoğunluklu Sunucular",
    "desc": "Tek kabinde en çok işlemciyi barındıran çok düğümlü gövdeler. HPC ve sanallaştırma için."
  }
];

export const products = [
  {
    "categorySlug": "rack-sunucular",
    "slug": "sr650-v4",
    "status": "PUBLISHED" as const,
    "sort": 0,
    "model": "ThinkSystem SR650 V4",
    "title": "Çift soketli 2U ana iş gücü",
    "desc": "Sanallaştırma, veritabanı ve karma iş yükleri için en çok tercih edilen 2U gövde.",
    "datasheetUrl": "",
    "formFactor": "2U raf",
    "processor": "2x Intel Xeon 6 işlemciye kadar",
    "gpu": "8x tek genişlik veya 3x çift genişlik GPU",
    "memory": "32x TruDDR5 yuva, 8 TB’a kadar",
    "driveBays": "20x 3,5\" veya 40x 2,5\" sürücüye kadar",
    "expansionSlots": "12x PCIe 5.0 yuvaya kadar; 1x OCP 3.0"
  },
  {
    "categorySlug": "rack-sunucular",
    "slug": "sr630-v4",
    "status": "PUBLISHED" as const,
    "sort": 1,
    "model": "ThinkSystem SR630 V4",
    "title": "Yoğun ortamlar için 1U",
    "desc": "Kabin alanının kısıtlı olduğu yerlerde çift soketli performans.",
    "datasheetUrl": "",
    "formFactor": "1U raf",
    "processor": "2x Intel Xeon 6 işlemciye kadar",
    "gpu": "3x tek genişlik GPU’ya kadar",
    "memory": "32x TruDDR5 yuva, 4 TB’a kadar",
    "driveBays": "12x 2,5\" veya 16x EDSFF sürücüye kadar",
    "expansionSlots": "3x PCIe 5.0 yuva; 1x OCP 3.0"
  },
  {
    "categorySlug": "rack-sunucular",
    "slug": "sr665-v3",
    "status": "PUBLISHED" as const,
    "sort": 2,
    "model": "ThinkSystem SR665 V3",
    "title": "AMD EPYC ile 2U",
    "desc": "Çekirdek başına yoğunluk arayan sanallaştırma ve analitik iş yükleri için.",
    "datasheetUrl": "",
    "formFactor": "2U raf",
    "processor": "2x 4. veya 5. nesil AMD EPYC işlemciye kadar",
    "gpu": "8x tek genişlik LP veya 3x çift genişlik GPU",
    "memory": "24x TruDDR5 yuva, 3DS RDIMM ile 6 TB’a kadar",
    "driveBays": "20x 3,5\" veya 40x 2,5\" sürücüye kadar",
    "expansionSlots": "12x PCIe yuvaya kadar (9x PCIe 5.0); 1x OCP 3.0"
  },
  {
    "categorySlug": "rack-sunucular",
    "slug": "sr645-v3",
    "status": "PUBLISHED" as const,
    "sort": 3,
    "model": "ThinkSystem SR645 V3",
    "title": "AMD EPYC ile 1U",
    "desc": "Tek üniteye sığan çift soketli AMD performansı; grafik yoğun iş yükleri için GPU desteği.",
    "datasheetUrl": "",
    "formFactor": "1U raf",
    "processor": "2x 4. veya 5. nesil AMD EPYC işlemciye kadar",
    "gpu": "4x tek genişlik GPU’ya kadar",
    "memory": "24x TruDDR5 RDIMM yuva",
    "driveBays": "4x 3,5\", 12x 2,5\" veya 16x EDSFF sürücü",
    "expansionSlots": "3x PCIe 4.0 + 2x PCIe 5.0 yuva; 1x OCP 3.0"
  },
  {
    "categorySlug": "rack-sunucular",
    "slug": "sr655-v3",
    "status": "PUBLISHED" as const,
    "sort": 4,
    "model": "ThinkSystem SR655 V3",
    "title": "Tek soketli 2U",
    "desc": "İki soketin maliyetine girmeden yüksek çekirdek sayısı isteyen iş yükleri için.",
    "datasheetUrl": "",
    "formFactor": "2U raf",
    "processor": "1x 4. nesil AMD EPYC, 96 çekirdeğe kadar",
    "gpu": "3x çift genişlik GPU’ya kadar",
    "memory": "12x TruDDR5 yuva, 3 TB’a kadar",
    "driveBays": "20x 3,5\" veya 40x 2,5\" sürücüye kadar",
    "expansionSlots": "8x PCIe 5.0 yuvaya kadar"
  },
  {
    "categorySlug": "rack-sunucular",
    "slug": "sr250-v3",
    "status": "PUBLISHED" as const,
    "sort": 5,
    "model": "ThinkSystem SR250 V3",
    "title": "Giriş seviyesi tek soket 1U",
    "desc": "Küçük ofis ve şube için uygun maliyetli, tek işlemcili raf sunucusu.",
    "datasheetUrl": "",
    "formFactor": "1U raf",
    "processor": "1x Intel Xeon E-2400/6300 serisi",
    "gpu": "Opsiyonel NVIDIA Quadro T1000 veya T400",
    "memory": "4x UDIMM yuva, 128 GB TruDDR5 4400MHz ECC’ye kadar",
    "driveBays": "4x 3,5\" veya 10x 2,5\" HDD/SSD; M.2 NVMe",
    "expansionSlots": "1x PCIe Gen5 x16 veya 2x PCIe Gen4 x8"
  },
  {
    "categorySlug": "kule-sunucular",
    "slug": "st650-v3",
    "status": "PUBLISHED" as const,
    "sort": 0,
    "model": "ThinkSystem ST650 V3",
    "title": "Ofiste çalışabilen kule",
    "desc": "Sessiz çalışma ve geniş disk kapasitesi; kabin gerektirmez, istenirse rafa da monte edilir.",
    "datasheetUrl": "",
    "formFactor": "4U kule (rafa monte edilebilir)",
    "processor": "2x Intel Xeon Silver/Gold işlemciye kadar",
    "gpu": "2x çift genişlik GPU’ya kadar",
    "memory": "32x TruDDR5 yuva, 2 TB’a kadar",
    "driveBays": "16x 3,5\" veya 32x 2,5\" sürücüye kadar",
    "expansionSlots": "9x PCIe yuvaya kadar"
  },
  {
    "categorySlug": "kule-sunucular",
    "slug": "st250-v3",
    "status": "PUBLISHED" as const,
    "sort": 1,
    "model": "ThinkSystem ST250 V3",
    "title": "Küçük işletme kulesi",
    "desc": "İlk sunucusunu alan işletmeler için; masa altında sessizce çalışır.",
    "datasheetUrl": "",
    "formFactor": "4U kule",
    "processor": "1x Intel Xeon E-2400 serisi",
    "gpu": "Opsiyonel giriş seviyesi GPU",
    "memory": "4x UDIMM yuva, 128 GB’a kadar",
    "driveBays": "8x 3,5\" veya 16x 2,5\" sürücüye kadar",
    "expansionSlots": "4x PCIe yuva"
  },
  {
    "categorySlug": "kule-sunucular",
    "slug": "st50-v3",
    "status": "PUBLISHED" as const,
    "sort": 2,
    "model": "ThinkSystem ST50 V3",
    "title": "En kompakt kule",
    "desc": "Dosya paylaşımı ve yedekleme gibi tek işli senaryolar için giriş seviyesi gövde.",
    "datasheetUrl": "",
    "formFactor": "4U kompakt kule",
    "processor": "1x Intel Xeon E-2400 serisi",
    "gpu": "—",
    "memory": "4x UDIMM yuva, 128 GB’a kadar",
    "driveBays": "4x 3,5\" sürücü",
    "expansionSlots": "2x PCIe yuva"
  },
  {
    "categorySlug": "gpu-ai-sunuculari",
    "slug": "sr675-v3",
    "status": "PUBLISHED" as const,
    "sort": 0,
    "model": "ThinkSystem SR675 V3",
    "title": "8 GPU’ya kadar 3U",
    "desc": "Model eğitimi ve çıkarım için yüksek GPU yoğunluğu; hava ve sıvı soğutma seçenekleri.",
    "datasheetUrl": "",
    "formFactor": "3U raf",
    "processor": "2x AMD EPYC 9004/9005 serisi",
    "gpu": "8x NVIDIA H100/H200 veya 4x çift genişlik GPU",
    "memory": "24x TruDDR5 yuva, 3 TB’a kadar",
    "driveBays": "8x 2,5\" NVMe/SATA sürücüye kadar",
    "expansionSlots": "10x PCIe 5.0 yuvaya kadar"
  },
  {
    "categorySlug": "gpu-ai-sunuculari",
    "slug": "sr680a-v4",
    "status": "PUBLISHED" as const,
    "sort": 1,
    "model": "ThinkSystem SR680a V4",
    "title": "Sekiz SXM GPU ile 8U",
    "desc": "Büyük dil modeli eğitimi için NVSwitch bağlantılı HGX platformu.",
    "datasheetUrl": "",
    "formFactor": "8U raf",
    "processor": "2x Intel Xeon 6 (Granite Rapids SP), 350W’a kadar",
    "gpu": "8x NVIDIA HGX B300 SXM (CX8 NVSwitch)",
    "memory": "32x TruDDR5 RDIMM, 6400MHz, 4 TB’a kadar",
    "driveBays": "8x 2,5\" hot-swap NVMe + 2x M.2 NVMe boot",
    "expansionSlots": "4x PCIe Gen5 x16 FHHL, 1x OCP, 8x OSFP"
  },
  {
    "categorySlug": "gpu-ai-sunuculari",
    "slug": "sr780a-v3",
    "status": "PUBLISHED" as const,
    "sort": 2,
    "model": "ThinkSystem SR780a V3",
    "title": "Sıvı soğutmalı 5U",
    "desc": "Neptune sıvı soğutma ile yüksek güçlü GPU’ları sessiz ve verimli çalıştırır.",
    "datasheetUrl": "",
    "formFactor": "5U raf (Neptune sıvı soğutma)",
    "processor": "2x Intel Xeon 4./5. nesil",
    "gpu": "4x NVIDIA HGX H100 SXM",
    "memory": "32x TruDDR5 yuva, 4 TB’a kadar",
    "driveBays": "8x 2,5\" NVMe sürücü",
    "expansionSlots": "6x PCIe 5.0 yuva"
  },
  {
    "categorySlug": "edge-sunucular",
    "slug": "se455-v3",
    "status": "PUBLISHED" as const,
    "sort": 0,
    "model": "ThinkEdge SE455 V3",
    "title": "Saha için 2U kısa gövde",
    "desc": "Sunucu odası olmayan yerler için kısa derinlikli, tozdan ve sıcaktan etkilenmeyen tasarım.",
    "datasheetUrl": "",
    "formFactor": "2U kısa derinlik (raf/duvar)",
    "processor": "1x AMD EPYC 8004 serisi",
    "gpu": "2x çift genişlik GPU’ya kadar",
    "memory": "6x TruDDR5 yuva, 576 GB’a kadar",
    "driveBays": "4x 3,5\" veya 8x 2,5\" sürücü",
    "expansionSlots": "4x PCIe 5.0 yuva"
  },
  {
    "categorySlug": "edge-sunucular",
    "slug": "se350-v2",
    "status": "PUBLISHED" as const,
    "sort": 1,
    "model": "ThinkEdge SE350 V2",
    "title": "Duvara asılabilen kompakt gövde",
    "desc": "Mağaza, şube ve üretim sahası için; kilitli kapak ve fiziksel güvenlik özellikleriyle.",
    "datasheetUrl": "",
    "formFactor": "1U yarım genişlik / duvara monte",
    "processor": "1x Intel Xeon D-2700 serisi",
    "gpu": "1x NVIDIA A2 veya L4",
    "memory": "4x DDR4 yuva, 256 GB’a kadar",
    "driveBays": "4x M.2 NVMe veya 2x 2,5\" SSD",
    "expansionSlots": "2x PCIe 4.0 x16 yuva"
  },
  {
    "categorySlug": "edge-sunucular",
    "slug": "se100",
    "status": "PUBLISHED" as const,
    "sort": 2,
    "model": "ThinkEdge SE100",
    "title": "Avuç içi boyutunda uç nokta",
    "desc": "Perakende kasası, kiosk ve şube dolabı gibi yer olmayan noktalar için en küçük gövde.",
    "datasheetUrl": "",
    "formFactor": "Ultra kompakt masaüstü / DIN ray",
    "processor": "1x Intel Core Ultra",
    "gpu": "Tümleşik NPU, opsiyonel NVIDIA L4",
    "memory": "2x SODIMM yuva, 96 GB’a kadar",
    "driveBays": "2x M.2 NVMe",
    "expansionSlots": "1x PCIe yuva"
  },
  {
    "categorySlug": "depolama",
    "slug": "dm-serisi",
    "status": "PUBLISHED" as const,
    "sort": 0,
    "model": "ThinkSystem DM Serisi",
    "title": "Birleşik (unified) depolama",
    "desc": "Blok, dosya ve nesne erişimini tek dizide toplar; buluta kademeleme desteğiyle.",
    "datasheetUrl": "",
    "formFactor": "2U–4U raf dizisi",
    "processor": "Çift denetleyici (aktif-aktif)",
    "gpu": "—",
    "memory": "256 GB’a kadar denetleyici önbelleği",
    "driveBays": "24x 2,5\" NVMe/SAS veya 12x 3,5\" sürücü",
    "expansionSlots": "32Gb FC, 25/100GbE bağlantı seçenekleri"
  },
  {
    "categorySlug": "depolama",
    "slug": "dg-serisi",
    "status": "PUBLISHED" as const,
    "sort": 1,
    "model": "ThinkSystem DG Serisi",
    "title": "Tam flash QLC dizi",
    "desc": "Yüksek kapasiteyi flash hızıyla birleştirir; yedekleme ve arşivden üretim yüklerine kadar.",
    "datasheetUrl": "",
    "formFactor": "2U raf dizisi",
    "processor": "Çift denetleyici",
    "gpu": "—",
    "memory": "—",
    "driveBays": "24x QLC NVMe SSD’ye kadar",
    "expansionSlots": "25/100GbE, 32Gb FC"
  },
  {
    "categorySlug": "depolama",
    "slug": "de-serisi",
    "status": "PUBLISHED" as const,
    "sort": 2,
    "model": "ThinkSystem DE Serisi",
    "title": "Blok tabanlı ekonomik dizi",
    "desc": "Sanallaştırma ve yedekleme için öngörülebilir performanslı, uygun maliyetli SAN.",
    "datasheetUrl": "",
    "formFactor": "2U–4U raf dizisi",
    "processor": "Çift denetleyici",
    "gpu": "—",
    "memory": "—",
    "driveBays": "60x 3,5\" sürücüye kadar (genişletme ile)",
    "expansionSlots": "16/32Gb FC, 10/25GbE iSCSI"
  },
  {
    "categorySlug": "yuksek-yogunluk",
    "slug": "sr670-v2",
    "status": "PUBLISHED" as const,
    "sort": 0,
    "model": "ThinkSystem SR670 V2",
    "title": "GPU yoğun 3U",
    "desc": "Sekiz adede kadar çift genişlik GPU’yu tek gövdede toplar; HPC ve görselleştirme için.",
    "datasheetUrl": "",
    "formFactor": "3U raf",
    "processor": "2x Intel Xeon 3. nesil",
    "gpu": "8x çift genişlik veya 4x SXM GPU",
    "memory": "32x DDR4 yuva, 4 TB’a kadar",
    "driveBays": "8x 2,5\" NVMe sürücü",
    "expansionSlots": "10x PCIe 4.0 yuva"
  },
  {
    "categorySlug": "yuksek-yogunluk",
    "slug": "sd650-v3",
    "status": "PUBLISHED" as const,
    "sort": 1,
    "model": "ThinkSystem SD650 V3",
    "title": "Sıvı soğutmalı çok düğümlü",
    "desc": "Neptune doğrudan su soğutma ile bir kabine en çok işlemciyi sığdıran HPC düğümü.",
    "datasheetUrl": "",
    "formFactor": "1U tepside 2 düğüm (6U muhafaza)",
    "processor": "Düğüm başına 2x Intel Xeon 4./5. nesil",
    "gpu": "Opsiyonel",
    "memory": "Düğüm başına 16x TruDDR5 yuva",
    "driveBays": "Düğüm başına 1x M.2 NVMe",
    "expansionSlots": "Düğüm başına 1x PCIe 5.0 x16"
  }
];

export const heroSlides = [
  {
    "status": "PUBLISHED" as const,
    "sort": 0,
    "theme": "light",
    "eyebrow": "Ürün Ailesi",
    "title": "1U'dan 8U'ya kadar her iş yükü",
    "body": "Rack, kule, uç nokta ve GPU sunucuları. Hangisinin size uyduğunu birlikte belirleriz.",
    "ctaLabel": "Kategorilere göz atın",
    "ctaHref": "/#urunler"
  },
  {
    "status": "PUBLISHED" as const,
    "sort": 1,
    "theme": "dark",
    "eyebrow": "Lenovo ThinkSystem",
    "title": "Lenovo ThinkSystem Sunucular",
    "body": "Stoktan teslim, yerinde kurulum, resmi garanti.",
    "ctaLabel": "Ürünleri inceleyin",
    "ctaHref": "/#urunler"
  },
  {
    "status": "PUBLISHED" as const,
    "sort": 2,
    "theme": "dark",
    "eyebrow": "",
    "title": "Lenovo 360 Platinum iş ortağı",
    "body": "Faturalı, resmi garantili donanım. Kurulumu ve satış sonrası desteği kendi ekibimiz yürütür.",
    "ctaLabel": "Teklif alın",
    "ctaHref": "/teklif"
  }
];
